version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: firebase-tools
    versions:
    - 9.1.0
    - 9.2.2
  - dependency-name: ionicons
    versions:
    - 5.2.3
    - 5.4.0
  - dependency-name: "@sentry/browser"
    versions:
    - 5.29.2
    - 6.0.3
  - dependency-name: "@ionic-native/status-bar"
    versions:
    - 5.30.0
  - dependency-name: "@ionic-native/splash-screen"
    versions:
    - 5.30.0
  - dependency-name: rxjs
    versions:
    - 6.6.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
