# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      -
        image: 'circleci/node:8.11.3'
    working_directory: ~/repo
    steps:
      - checkout
      -
        run:
          name: 'Install Ionic and Cordova'
          command: 'sudo npm i -g ionic@3.20.0 cordova@8.0.0'
      -
        restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      -
        run:
          name: 'Install Node Modules'
          command: 'npm install'
      -
        save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      -
        run:
          name: 'Build PWA'
          command: 'npm run ionic:build'
      -
        run:
          name: 'Deploy to Firebase'
          command: './node_modules/firebase-tools/bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN'

      
workflows:
  version: 2
  build-and-deploy:
    jobs:
      -
        build:
          filters:
            branches:
              only: master
