# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/ for more details
#
version: 2.1

executors:
  tabify-executor:
    docker:
      - image: circleci/node:12.16.0
    working_directory: ~/repo

jobs:
  build:
    executor: tabify-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build Ionic application
          command: npm run build --prod
      - persist_to_workspace:
          root: .
          paths:
            - www
            - package.json
            - firebase.json
            - .firebaserc
            - node_modules
  deploy:
    executor: tabify-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
