export enum TicketUpdates {
    TICKET_USER_ADDED = 'TICKET_USER_ADDED',
    TICKET_USER_REMOVED = 'TICKET_USER_REMOVED',
    TICKET_ITEM_USERS_UPDATED = 'TICKET_ITEM_USERS_UPDATED',
    TICKET_PAYMENTS_UPDATED = 'TICKET_PAYMENTS_UPDATED',
}
